# 変更したら、docker-compose down -> docker-compose up で変更を反映させる
# 自由に設定できるポート番号は、49152から65535
version: '3'
services:
  web:
    image: php:7.2-apache
    volumes:
      - .:/var/www/html
    command: |
      bash -c "echo 'output_buffering = 4096' >> /usr/local/etc/php/php.ini &&
              echo 'error_reporting = E_ALL' >> /usr/local/etc/php/php.ini &&
              echo 'default_charset = UTF-8' >> /usr/local/etc/php/php.ini &&
              echo 'date.timezone = Asia/Tokyo' >> /usr/local/etc/php/php.ini &&
              echo 'display_errors = On' >> /usr/local/etc/php/php.ini &&
              apache2-foreground"
    ports:
      - 49152:80
    depends_on:
      - db
  db:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=user
      - PMA_PASSWORD=password
    ports:
      - 49153:80
    volumes:
      - ./phpmyadmin/sessions:/sessions
volumes:
  db_data: